#!/bin/bash
#

function log_daemon {
	INFO "${LOG_PREFIX}: $@" >  /dev/ttyO0
	INFO "${LOG_PREFIX}: $@" >> ${DAEMON_SHARE_LOG}
	INFO "${LOG_PREFIX}: $@"
	echo -e "${LOG_PREFIX}: $@" | sed -r 's/'$(echo -e "\033")'\[[0-9]{1,2}(;([0-9]{1,2})?)?[mK]//g' > /dev/kmsg
}

function fn_exist {
	declare -f -F $1 > /dev/null
	return $?
}

function run_daemon {
	export LOG_LINE_END="\\r"
	export LOG_PREFIX="yapps/$(basename $0)"
	local EXIT_CODE="0"
	local HOOK_ENTER="yapps_launch_hook_enter"
	local HOOK_EXIT="yapps_launch_hook_exit"

	# Record the timestamp.
	#
	date '+%Y%m%d%H%M'

	while true; do
		# Initialize YAPPS_xxx environment variables, such as
		#   - YAPPS_LOGGER_PRECISE_TIMESTAMP
		#   - YAPPS_DUMP_LOADED_CONFIG
		#   - YAPPS_TOE_LINUX_BOOTS
		#   - YAPPS_EXTRA_PLUGINS
		#   - YAPPS_DAEMON_HOOK_SCRIPT
		#
		init_yapps_variables

		# Load hook script for the daemon
		#
		if [ "" != "${YAPPS_DAEMON_HOOK_SCRIPT}" ] && [ -f "${YAPPS_DAEMON_HOOK_SCRIPT}" ]; then
			INFO "$0 loads hook script $(YELLOW ${YAPPS_DAEMON_HOOK_SCRIPT}) ..."
			source ${YAPPS_DAEMON_HOOK_SCRIPT}
		else
			log_daemon "missing hook script $(YELLOW ${YAPPS_DAEMON_HOOK_SCRIPT}) => ignored."
		fi

		# Run `yapps_launch_hook_enter()` if available.
		#
		fn_exist ${HOOK_ENTER} && INFO "[$(GRAY ${YAPPS_DAEMON_HOOK_SCRIPT})] $(LIGHT_GREEN ${HOOK_ENTER}) $(BLUE $@)" && ${HOOK_ENTER} $@

		# Run nodejs daemon synchronously, and capture its exit-code.
		#
		log_daemon "$(LIGHT_GREEN $@)"
		echo "YYY-------------------------"
		$@; EXIT_CODE=$?
		echo "ZZZ-------------------------"
		log_daemon "exit-code: ${EXIT_CODE}"

		# Run `yapps_launch_hook_exit()` if available.
		#
		fn_exist ${HOOK_EXIT} && INFO "[$(GRAY ${YAPPS_DAEMON_HOOK_SCRIPT})] $(LIGHT_GREEN ${HOOK_EXIT}) $(BLUE ${EXIT_CODE})" && ${HOOK_EXIT} ${EXIT_CODE}

		case "${EXIT_CODE}" in
			0)
				log_daemon "peaceful shutdown with exit-code (0)"
				break
				;;
			96)
				##
				# Peaceful shutdown in Yapps. https://github.com/yagamy4680/yapps/blob/master/lib/classes/BaseApp.ls#L226-L231
				#
				log_daemon "peaceful restart with exit-code (96)"
				continue
				;;
			137)
				##
				# Forced shutdown in nodejs: https://nodejs.org/api/process.html#process_signal_events
				#
				log_daemon "forcedly shutdown with exit-code (137), maybe caused by SIGKILL(9)"
				break
				;;
			140)
				##
				# Peaceful restart in order to reload configs in Yapps.
				#
				log_daemon "peaceful restart to reload configs with exit-code (140)"
				continue
				;;
			*)
				log_daemon "unexpected shutdown with code (${EXIT_CODE})"
				continue
				;;
		esac
	done
}
