#!/bin/bash

## print header lines
while IFS= read -r line; do

	## test line contenst and parse as required
	[[ "$line" =~ Address ]] && mac=${line##*ss: }
	[[ "$line" =~ \(Channel ]] && { chn=${line##*nel }; chn=${chn:0:$((${#chn}-1))}; }
	[[ "$line" =~ Frequen ]] && { frq=${line##*ncy:}; frq=${frq%% *}; }
	[[ "$line" =~ Quality ]] && { 
		qual=${line##*ity=}
		qual=${qual%% *}
		lvl=${line##*evel=}
		lvl=${lvl%% *}
	}
	[[ "$line" =~ Encrypt ]] && enc=${line##*key:}
	[[ "$line" =~ ESSID ]] && {
		essid=${line##*ID:}
		# echo "$mac  $essid  $frq  $chn  $qual  $lvl  $enc"  # output after ESSID
		echo "$(echo $essid | tr '"' ' ' | sed 's/ *//g')"
	}

done
