#!/bin/bash
#
##DOC:	startup an app in current profile.

function GET_DAEMON_CONFIG {
	local NAME=$1
	local KEY=$2
	case "${KEY}" in
		pid_file)
			echo "${YAC_RUN_DIR}/${NAME}.pid"
			;;
		ppid_file)
			echo "${YAC_RUN_DIR}/${NAME}.pid.ppid"
			;;
		unixsock_file)
			echo "${YAC_RUN_DIR}/${NAME}.sock"
			;;
		*)
			;;
	esac
}

function DUMP_YAPPS_VARIABLES {
	local TMP_FILE=$(mktemp /tmp/XXXXXX)
	local NAMES=($(env | grep "^YAPPS_" | sort | awk -F'=' '{print $1}'))
	for name in "${NAMES[@]}"; do
		local value=${!name}
		echo -e "\texport ${name}=\"${value}\""
	done
}

function GENERATE_NODEJS_DAEMON_SCRIPT {
cat <<__EOF__
#!/bin/bash
#
$(cat ${YAC_DIR}/helpers/nodejs_daemon | grep -v "^#")

# Yapps Variable Initialization
#
function init_yapps_variables {
$(DUMP_YAPPS_VARIABLES)
	rm -f $(GET_DAEMON_CONFIG ${APP_ALIAS} pid_file)
	rm -f $(GET_DAEMON_CONFIG ${APP_ALIAS} ppid_file)
	rm -f $(GET_DAEMON_CONFIG ${APP_ALIAS} unixsock_file)
	return 0
}

# External BASH scripts
#
source ${YAC_DIR}/externals/bash-utils/verbose
init_verbose \$0

# System Variables
#
export NODE_PATH="${APP_RUNTIME_MODULE_PATH}"
export DAEMON_SHARE_LOG="${DAEMON_SHARE_LOG}"

# Entry-Point
#
run_daemon $@
__EOF__
}

function RUN_NODE_APP_DAEMON {
	local DAEMON_DIR="${PROFILE_CURRENT_DIR}/daemons"
	local DAEMON_SCRIPT="${DAEMON_DIR}/${APP_ALIAS}"
	local DAEMON_SHARE_LOG="${PROFILE_LOG_DIR}/daemons.log"
	INFO "preparing daemon script: $(LIGHT_GREEN ${DAEMON_SCRIPT})"
	mkdir -p ${DAEMON_DIR}

	DAEMON_SHARE_LOG=${DAEMON_SHARE_LOG} \
		GENERATE_NODEJS_DAEMON_SCRIPT \
			${APP_RUNTIME_EXECUTABLE} \
			${APP_RUNTIME_OPTS} \
			${APP_ENTRY} \
			${APP_OPTS} \
			$@ \
		> ${DAEMON_SCRIPT}

	nohup ${BASH} ${DAEMON_SCRIPT} >> ${APP_LOGFILE} 2>&1&
}

